import matplotlib.pyplot as plt
import matplotlib.patches as patches
import math
import io
from PIL import Image


class ParkingVisualizer:
    """
    Autonomous parking visualization (rear-axle center modeling).
    """

    def __init__(self, figsize=(12, 8)):
        plt.ion()
        self.fig, self.ax = plt.subplots(figsize=figsize)
        self.ax.set_aspect('equal')

        self.colors = {
            "vehicle": "royalblue",
            "obstacle": "firebrick",
            "parking": "seagreen",
            "path": "purple",
            "start": "cyan",
            "goal": "magenta",
        }

        self.vehicle_patch = None
        self.path_line = None
        self.rear_point = None
        self.front_wheel_arrow = None
        self.trajectory_line = None
        self.info_text = None
        self.frames = []

    # =====================================================
    # Scene
    # =====================================================
    def draw_scene(self, scene, start_pose=None, goal_pose=None):
        self.ax.clear()

        # Clearing axes invalidates existing artists; reset handles
        self.vehicle_patch = None
        self.path_line = None
        self.rear_point = None
        self.front_wheel_arrow = None
        self.trajectory_line = None
        self.info_text = None

        if scene.boundary:
            x0, x1, y0, y1 = scene.boundary
            self.ax.set_xlim(x0, x1)
            self.ax.set_ylim(y0, y1)

        self.ax.set_xlabel("X (m)")
        self.ax.set_ylabel("Y (m)")
        self.ax.set_title("Autonomous Parking Visualization")
        self.ax.grid(True, linestyle="--", alpha=0.3)

        # Parking slots.
        for i, slot in enumerate(scene.parking_spaces):
            poly = scene._slot_polygon(slot)
            patch = patches.Polygon(
                poly,
                closed=True,
                alpha=0.25,
                color=self.colors["parking"],
                label="target slot" if i == scene.target_idx else None,
            )
            self.ax.add_patch(patch)

            cx, cy = slot["center"]
            th = slot["theta"]
            dx = 2.0 * math.cos(th)
            dy = 2.0 * math.sin(th)
            self.ax.arrow(cx, cy, dx, dy, head_width=0.3, fc="green")

        # Obstacles.
        for obs in scene.obstacles:
            patch = patches.Polygon(
                obs, closed=True, alpha=0.7, color=self.colors["obstacle"]
            )
            self.ax.add_patch(patch)

        # Start / goal.
        if start_pose is not None:
            self._draw_pose(start_pose, self.colors["start"], "start")
        if goal_pose is not None:
            self._draw_pose(goal_pose, self.colors["goal"], "goal")

        self.ax.legend(loc="upper right")
        self.fig.canvas.draw()

    # =====================================================
    # Driven trajectory (actual vehicle path)
    # =====================================================
    def draw_trajectory(self, traj_points):
        if self.trajectory_line:
            try:
                self.trajectory_line.remove()
            except Exception:
                pass

        if len(traj_points) == 0:
            return

        xs = [p[0] for p in traj_points]
        ys = [p[1] for p in traj_points]
        self.trajectory_line, = self.ax.plot(
            xs,
            ys,
            '-',
            color='black',
            linewidth=1.5,
            label='driven trajectory'
        )
        self.fig.canvas.draw()

    # =====================================================
    # Pose
    # =====================================================
    def _draw_pose(self, pose, color, label):
        x, y, theta = pose
        self.ax.plot(x, y, "o", color=color, label=label)
        self.ax.arrow(
            x,
            y,
            1.5 * math.cos(theta),
            1.5 * math.sin(theta),
            head_width=0.3,
            fc=color,
        )

    # =====================================================
    # Vehicle
    # =====================================================
    def draw_vehicle(self, scene, x, y, theta, delta=0.0, collided=False, success=False):
        """
        Draw the vehicle (geometry generated by scene).
        """
        poly = scene.vehicle_polygon(x, y, theta)

        if self.vehicle_patch:
            try:
                self.vehicle_patch.remove()
            except Exception:
                # Artist may already be detached after ax.clear(); ignore
                pass

        if collided:
            color = "crimson"
        elif success:
            color = "limegreen"
        else:
            color = self.colors["vehicle"]

        self.vehicle_patch = patches.Polygon(
            poly,
            closed=True,
            alpha=0.85,
            color=color,
            label="vehicle",
        )
        self.ax.add_patch(self.vehicle_patch)

        # Rear-axle center.
        if self.rear_point:
            self.rear_point.remove()
        self.rear_point, = self.ax.plot(x, y, "ko", markersize=4)

        # Front wheel steering (illustration).
        L = scene.wheelbase
        fx = x + L * math.cos(theta)
        fy = y + L * math.sin(theta)

        wheel_angle = theta - delta  # Clockwise is positive.
        dx = 0.6 * math.cos(wheel_angle)
        dy = 0.6 * math.sin(wheel_angle)

        if self.front_wheel_arrow:
            try:
                self.front_wheel_arrow.remove()
            except Exception:
                pass

        self.front_wheel_arrow = self.ax.arrow(
            fx,
            fy,
            dx,
            dy,
            head_width=0.15,
            head_length=0.25,
            fc="black",
            ec="black",
        )

        self.fig.canvas.draw()

    # =====================================================
    # Path
    # =====================================================
    def draw_path(self, path):
        if self.path_line:
            try:
                self.path_line.remove()
            except Exception:
                pass
        xs = [p[0] for p in path]
        ys = [p[1] for p in path]

        # Draw the path and add markers at each waypoint.
        self.path_line, = self.ax.plot(
            xs,
            ys,
            linestyle="--",
            marker='o',
            markersize=4,
            color=self.colors["path"],
            linewidth=2,
            label="planned path",
        )
        self.fig.canvas.draw()

    # =====================================================
    # Info display
    # =====================================================
    def draw_info(self, info_str):
        if self.info_text:
            try:
                self.info_text.remove()
            except Exception:
                pass
        
        self.info_text = self.ax.text(
            0.02, 0.98, 
            info_str, 
            transform=self.ax.transAxes, 
            verticalalignment='top', 
            fontsize=10,
            fontfamily='monospace',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.8)
        )

    # =====================================================
    # Control
    # =====================================================
    def update(self, pause=0.01):
        self.fig.canvas.draw()
        plt.pause(pause)

    def capture_frame(self):
        """Capture current figure as an image frame."""
        buf = io.BytesIO()
        # Use a reasonable dpi to keep file size manageable
        self.fig.savefig(buf, format='png', dpi=80)
        buf.seek(0)
        img = Image.open(buf).copy()
        self.frames.append(img)
        buf.close()

    def save_gif(self, filename="parking.gif", duration=100):
        """Save collected frames as a GIF."""
        if not self.frames:
            print("No frames to save.")
            return
        
        self.frames[0].save(
            filename,
            save_all=True,
            append_images=self.frames[1:],
            duration=duration,
            loop=0
        )
        print(f"Saved gif to {filename}")
        self.frames = []  # Clear frames after saving

    def save(self, filename="parking.png"):
        self.fig.savefig(filename, dpi=150, bbox_inches="tight")
        print(f"Saved figure to {filename}")

    def show(self):
        plt.ioff()
        plt.show()
